//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITMCServiceCenter.Web.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ITMCServiceCenterResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ITMCServiceCenterResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ITMCServiceCenter.Web.Domain.Resources.ITMCServiceCenterResource", typeof(ITMCServiceCenterResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string lblCancel {
            get {
                return ResourceManager.GetString("lblCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Writer.
        /// </summary>
        public static string lblChangeWriter {
            get {
                return ResourceManager.GetString("lblChangeWriter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string lblDelete {
            get {
                return ResourceManager.GetString("lblDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Details.
        /// </summary>
        public static string lblDetail {
            get {
                return ResourceManager.GetString("lblDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string lblEdit {
            get {
                return ResourceManager.GetString("lblEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string lblLogin {
            get {
                return ResourceManager.GetString("lblLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string lblNew {
            get {
                return ResourceManager.GetString("lblNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string lblSave {
            get {
                return ResourceManager.GetString("lblSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Name.
        /// </summary>
        public static string lblTaskName {
            get {
                return ResourceManager.GetString("lblTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string lblUserName {
            get {
                return ResourceManager.GetString("lblUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username or password you entered is incorrect..
        /// </summary>
        public static string msgIncorrectUserNameAndPassword {
            get {
                return ResourceManager.GetString("msgIncorrectUserNameAndPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Error. Please contact admin..
        /// </summary>
        public static string msgUserDisabled {
            get {
                return ResourceManager.GetString("msgUserDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approver.
        /// </summary>
        public static string resApprover {
            get {
                return ResourceManager.GetString("resApprover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned To.
        /// </summary>
        public static string resAssignedTo {
            get {
                return ResourceManager.GetString("resAssignedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string resCategory {
            get {
                return ResourceManager.GetString("resCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string resClient {
            get {
                return ResourceManager.GetString("resClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string resCreatedBy {
            get {
                return ResourceManager.GetString("resCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        public static string resCreatedOn {
            get {
                return ResourceManager.GetString("resCreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string resDescription {
            get {
                return ResourceManager.GetString("resDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date.
        /// </summary>
        public static string resEndDate {
            get {
                return ResourceManager.GetString("resEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Engineers.
        /// </summary>
        public static string resEngineers {
            get {
                return ResourceManager.GetString("resEngineers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated Cost.
        /// </summary>
        public static string resEstimatedCost {
            get {
                return ResourceManager.GetString("resEstimatedCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated Hours.
        /// </summary>
        public static string resEstimatedHours {
            get {
                return ResourceManager.GetString("resEstimatedHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impact.
        /// </summary>
        public static string resImpact {
            get {
                return ResourceManager.GetString("resImpact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implementation Team.
        /// </summary>
        public static string resImplementationTeam {
            get {
                return ResourceManager.GetString("resImplementationTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string resLevel {
            get {
                return ResourceManager.GetString("resLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        public static string resManager {
            get {
                return ResourceManager.GetString("resManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified By.
        /// </summary>
        public static string resModifiedBy {
            get {
                return ResourceManager.GetString("resModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified Date.
        /// </summary>
        public static string resModifiedOn {
            get {
                return ResourceManager.GetString("resModifiedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        public static string resModule {
            get {
                return ResourceManager.GetString("resModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent Complete.
        /// </summary>
        public static string resPercentComplete {
            get {
                return ResourceManager.GetString("resPercentComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO No..
        /// </summary>
        public static string resPoNo {
            get {
                return ResourceManager.GetString("resPoNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string resPriority {
            get {
                return ResourceManager.GetString("resPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string resProject {
            get {
                return ResourceManager.GetString("resProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Task Type.
        /// </summary>
        public static string resProjectTaskType {
            get {
                return ResourceManager.GetString("resProjectTaskType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Type.
        /// </summary>
        public static string resProjectType {
            get {
                return ResourceManager.GetString("resProjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QA.
        /// </summary>
        public static string resQA {
            get {
                return ResourceManager.GetString("resQA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QA End Date.
        /// </summary>
        public static string resQAEndDate {
            get {
                return ResourceManager.GetString("resQAEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QA Start Date.
        /// </summary>
        public static string resQAStartDate {
            get {
                return ResourceManager.GetString("resQAStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related To.
        /// </summary>
        public static string resRelatedTo {
            get {
                return ResourceManager.GetString("resRelatedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relate Type.
        /// </summary>
        public static string resRelatedType {
            get {
                return ResourceManager.GetString("resRelatedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested On.
        /// </summary>
        public static string resRequestedOn {
            get {
                return ResourceManager.GetString("resRequestedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requester.
        /// </summary>
        public static string resRequester {
            get {
                return ResourceManager.GetString("resRequester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        public static string resSite {
            get {
                return ResourceManager.GetString("resSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string resStartDate {
            get {
                return ResourceManager.GetString("resStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string resStatus {
            get {
                return ResourceManager.GetString("resStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string resTeam {
            get {
                return ResourceManager.GetString("resTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Type.
        /// </summary>
        public static string resTeamType {
            get {
                return ResourceManager.GetString("resTeamType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing Team.
        /// </summary>
        public static string resTestingTeam {
            get {
                return ResourceManager.GetString("resTestingTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string resTitle {
            get {
                return ResourceManager.GetString("resTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Requests.
        /// </summary>
        public static string titleChangeRequests {
            get {
                return ResourceManager.GetString("titleChangeRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incidents.
        /// </summary>
        public static string titleIncidents {
            get {
                return ResourceManager.GetString("titleIncidents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issues.
        /// </summary>
        public static string titleIssues {
            get {
                return ResourceManager.GetString("titleIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Documents.
        /// </summary>
        public static string titleProjectDocuments {
            get {
                return ResourceManager.GetString("titleProjectDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string titleProjects {
            get {
                return ResourceManager.GetString("titleProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Tasks.
        /// </summary>
        public static string titleProjectTasks {
            get {
                return ResourceManager.GetString("titleProjectTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Requests.
        /// </summary>
        public static string titleServiceRequests {
            get {
                return ResourceManager.GetString("titleServiceRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a client..
        /// </summary>
        public static string validationRequiredClientName {
            get {
                return ResourceManager.GetString("validationRequiredClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter password..
        /// </summary>
        public static string validationRequiredPassword {
            get {
                return ResourceManager.GetString("validationRequiredPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter title..
        /// </summary>
        public static string validationRequiredTitle {
            get {
                return ResourceManager.GetString("validationRequiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter username..
        /// </summary>
        public static string validationRequiredUserName {
            get {
                return ResourceManager.GetString("validationRequiredUserName", resourceCulture);
            }
        }
    }
}
