//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/02/12 - 15:04:35
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using ITMCServiceCenter.Web.Database;

namespace ITMCServiceCenter.Web.Domain
{

    /// <summary>
    /// Assembler for <see cref="tbl_TeamMember"/> and <see cref="tbl_TeamMemberDTO"/>.
    /// </summary>
    public static partial class tbl_TeamMember_Assembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="tbl_TeamMemberDTO"/> converted from <see cref="tbl_TeamMember"/>.</param>
        static partial void OnDTO(this tbl_TeamMember entity, tbl_TeamMemberDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="tbl_TeamMember"/> converted from <see cref="tbl_TeamMemberDTO"/>.</param>
        static partial void OnEntity(this tbl_TeamMemberDTO dto, tbl_TeamMember entity);

        /// <summary>
        /// Converts this instance of <see cref="tbl_TeamMemberDTO"/> to an instance of <see cref="tbl_TeamMember"/>.
        /// </summary>
        /// <param name="dto"><see cref="tbl_TeamMemberDTO"/> to convert.</param>
        public static tbl_TeamMember ToEntity(this tbl_TeamMemberDTO dto)
        {
            if (dto == null) return null;

            var entity = new tbl_TeamMember();

            entity.Id = dto.Id;
            entity.TeamId = dto.TeamId;
            entity.UserId = dto.UserId;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="tbl_TeamMember"/> to an instance of <see cref="tbl_TeamMemberDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="tbl_TeamMember"/> to convert.</param>
        public static tbl_TeamMemberDTO ToDTO(this tbl_TeamMember entity)
        {
            if (entity == null) return null;

            var dto = new tbl_TeamMemberDTO();

            dto.Id = entity.Id;
            dto.TeamId = entity.TeamId;
            dto.UserId = entity.UserId;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="tbl_TeamMemberDTO"/> to an instance of <see cref="tbl_TeamMember"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<tbl_TeamMember> ToEntities(this IEnumerable<tbl_TeamMemberDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="tbl_TeamMember"/> to an instance of <see cref="tbl_TeamMemberDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<tbl_TeamMemberDTO> ToDTOs(this IEnumerable<tbl_TeamMember> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
