//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/02/12 - 15:04:34
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using ITMCServiceCenter.Web.Database;

namespace ITMCServiceCenter.Web.Domain
{

    /// <summary>
    /// Assembler for <see cref="tbl_IncidentAction"/> and <see cref="tbl_IncidentActionDTO"/>.
    /// </summary>
    public static partial class tbl_IncidentAction_Assembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="tbl_IncidentActionDTO"/> converted from <see cref="tbl_IncidentAction"/>.</param>
        static partial void OnDTO(this tbl_IncidentAction entity, tbl_IncidentActionDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="tbl_IncidentAction"/> converted from <see cref="tbl_IncidentActionDTO"/>.</param>
        static partial void OnEntity(this tbl_IncidentActionDTO dto, tbl_IncidentAction entity);

        /// <summary>
        /// Converts this instance of <see cref="tbl_IncidentActionDTO"/> to an instance of <see cref="tbl_IncidentAction"/>.
        /// </summary>
        /// <param name="dto"><see cref="tbl_IncidentActionDTO"/> to convert.</param>
        public static tbl_IncidentAction ToEntity(this tbl_IncidentActionDTO dto)
        {
            if (dto == null) return null;

            var entity = new tbl_IncidentAction();

            entity.Id = dto.Id;
            entity.IncidentId = dto.IncidentId;
            entity.Action = dto.Action;
            entity.CreatedBy = dto.CreatedBy;
            entity.CreatedOn = dto.CreatedOn;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="tbl_IncidentAction"/> to an instance of <see cref="tbl_IncidentActionDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="tbl_IncidentAction"/> to convert.</param>
        public static tbl_IncidentActionDTO ToDTO(this tbl_IncidentAction entity)
        {
            if (entity == null) return null;

            var dto = new tbl_IncidentActionDTO();

            dto.Id = entity.Id;
            dto.IncidentId = entity.IncidentId;
            dto.Action = entity.Action;
            dto.CreatedBy = entity.CreatedBy;
            dto.CreatedOn = entity.CreatedOn;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="tbl_IncidentActionDTO"/> to an instance of <see cref="tbl_IncidentAction"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<tbl_IncidentAction> ToEntities(this IEnumerable<tbl_IncidentActionDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="tbl_IncidentAction"/> to an instance of <see cref="tbl_IncidentActionDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<tbl_IncidentActionDTO> ToDTOs(this IEnumerable<tbl_IncidentAction> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
