//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/02/12 - 15:04:35
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using ITMCServiceCenter.Web.Database;

namespace ITMCServiceCenter.Web.Domain
{

    /// <summary>
    /// Assembler for <see cref="tbl_RelatedIssue"/> and <see cref="tbl_RelatedIssueDTO"/>.
    /// </summary>
    public static partial class tbl_RelatedIssue_Assembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="tbl_RelatedIssueDTO"/> converted from <see cref="tbl_RelatedIssue"/>.</param>
        static partial void OnDTO(this tbl_RelatedIssue entity, tbl_RelatedIssueDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="tbl_RelatedIssue"/> converted from <see cref="tbl_RelatedIssueDTO"/>.</param>
        static partial void OnEntity(this tbl_RelatedIssueDTO dto, tbl_RelatedIssue entity);

        /// <summary>
        /// Converts this instance of <see cref="tbl_RelatedIssueDTO"/> to an instance of <see cref="tbl_RelatedIssue"/>.
        /// </summary>
        /// <param name="dto"><see cref="tbl_RelatedIssueDTO"/> to convert.</param>
        public static tbl_RelatedIssue ToEntity(this tbl_RelatedIssueDTO dto)
        {
            if (dto == null) return null;

            var entity = new tbl_RelatedIssue();

            entity.Id = dto.Id;
            entity.RelatedIssueId = dto.RelatedIssueId;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="tbl_RelatedIssue"/> to an instance of <see cref="tbl_RelatedIssueDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="tbl_RelatedIssue"/> to convert.</param>
        public static tbl_RelatedIssueDTO ToDTO(this tbl_RelatedIssue entity)
        {
            if (entity == null) return null;

            var dto = new tbl_RelatedIssueDTO();

            dto.Id = entity.Id;
            dto.RelatedIssueId = entity.RelatedIssueId;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="tbl_RelatedIssueDTO"/> to an instance of <see cref="tbl_RelatedIssue"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<tbl_RelatedIssue> ToEntities(this IEnumerable<tbl_RelatedIssueDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="tbl_RelatedIssue"/> to an instance of <see cref="tbl_RelatedIssueDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<tbl_RelatedIssueDTO> ToDTOs(this IEnumerable<tbl_RelatedIssue> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
