//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/02/12 - 15:04:33
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using ITMCServiceCenter.Web.Database;

namespace ITMCServiceCenter.Web.Domain
{

    /// <summary>
    /// Assembler for <see cref="tbl_ChangeRequestDocument"/> and <see cref="tbl_ChangeRequestDocumentDTO"/>.
    /// </summary>
    public static partial class tbl_ChangeRequestDocument_Assembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="tbl_ChangeRequestDocumentDTO"/> converted from <see cref="tbl_ChangeRequestDocument"/>.</param>
        static partial void OnDTO(this tbl_ChangeRequestDocument entity, tbl_ChangeRequestDocumentDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="tbl_ChangeRequestDocument"/> converted from <see cref="tbl_ChangeRequestDocumentDTO"/>.</param>
        static partial void OnEntity(this tbl_ChangeRequestDocumentDTO dto, tbl_ChangeRequestDocument entity);

        /// <summary>
        /// Converts this instance of <see cref="tbl_ChangeRequestDocumentDTO"/> to an instance of <see cref="tbl_ChangeRequestDocument"/>.
        /// </summary>
        /// <param name="dto"><see cref="tbl_ChangeRequestDocumentDTO"/> to convert.</param>
        public static tbl_ChangeRequestDocument ToEntity(this tbl_ChangeRequestDocumentDTO dto)
        {
            if (dto == null) return null;

            var entity = new tbl_ChangeRequestDocument();

            entity.Id = dto.Id;
            entity.ChangeRequestId = dto.ChangeRequestId;
            entity.Title = dto.Title;
            entity.Description = dto.Description;
            entity.Path = dto.Path;
            entity.CreatedBy = dto.CreatedBy;
            entity.CreatedOn = dto.CreatedOn;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="tbl_ChangeRequestDocument"/> to an instance of <see cref="tbl_ChangeRequestDocumentDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="tbl_ChangeRequestDocument"/> to convert.</param>
        public static tbl_ChangeRequestDocumentDTO ToDTO(this tbl_ChangeRequestDocument entity)
        {
            if (entity == null) return null;

            var dto = new tbl_ChangeRequestDocumentDTO();

            dto.Id = entity.Id;
            dto.ChangeRequestId = entity.ChangeRequestId;
            dto.Title = entity.Title;
            dto.Description = entity.Description;
            dto.Path = entity.Path;
            dto.CreatedBy = entity.CreatedBy;
            dto.CreatedOn = entity.CreatedOn;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="tbl_ChangeRequestDocumentDTO"/> to an instance of <see cref="tbl_ChangeRequestDocument"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<tbl_ChangeRequestDocument> ToEntities(this IEnumerable<tbl_ChangeRequestDocumentDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="tbl_ChangeRequestDocument"/> to an instance of <see cref="tbl_ChangeRequestDocumentDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<tbl_ChangeRequestDocumentDTO> ToDTOs(this IEnumerable<tbl_ChangeRequestDocument> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
