//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/02/12 - 15:04:33
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using ITMCServiceCenter.Web.Database;

namespace ITMCServiceCenter.Web.Domain
{

    /// <summary>
    /// Assembler for <see cref="tbl_Assignee"/> and <see cref="tbl_AssigneeDTO"/>.
    /// </summary>
    public static partial class tbl_Assignee_Assembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="tbl_AssigneeDTO"/> converted from <see cref="tbl_Assignee"/>.</param>
        static partial void OnDTO(this tbl_Assignee entity, tbl_AssigneeDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="tbl_Assignee"/> converted from <see cref="tbl_AssigneeDTO"/>.</param>
        static partial void OnEntity(this tbl_AssigneeDTO dto, tbl_Assignee entity);

        /// <summary>
        /// Converts this instance of <see cref="tbl_AssigneeDTO"/> to an instance of <see cref="tbl_Assignee"/>.
        /// </summary>
        /// <param name="dto"><see cref="tbl_AssigneeDTO"/> to convert.</param>
        public static tbl_Assignee ToEntity(this tbl_AssigneeDTO dto)
        {
            if (dto == null) return null;

            var entity = new tbl_Assignee();

            entity.RelateTypeId = dto.RelateTypeId;
            entity.RelatedToId = dto.RelatedToId;
            entity.UserId = dto.UserId;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="tbl_Assignee"/> to an instance of <see cref="tbl_AssigneeDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="tbl_Assignee"/> to convert.</param>
        public static tbl_AssigneeDTO ToDTO(this tbl_Assignee entity)
        {
            if (entity == null) return null;

            var dto = new tbl_AssigneeDTO();

            dto.RelateTypeId = entity.RelateTypeId;
            dto.RelatedToId = entity.RelatedToId;
            dto.UserId = entity.UserId;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="tbl_AssigneeDTO"/> to an instance of <see cref="tbl_Assignee"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<tbl_Assignee> ToEntities(this IEnumerable<tbl_AssigneeDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="tbl_Assignee"/> to an instance of <see cref="tbl_AssigneeDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<tbl_AssigneeDTO> ToDTOs(this IEnumerable<tbl_Assignee> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
