//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/02/12 - 15:04:34
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using ITMCServiceCenter.Web.Database;

namespace ITMCServiceCenter.Web.Domain
{

    /// <summary>
    /// Assembler for <see cref="tbl_IssueTracker"/> and <see cref="tbl_IssueTrackerDTO"/>.
    /// </summary>
    public static partial class tbl_IssueTracker_Assembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="tbl_IssueTrackerDTO"/> converted from <see cref="tbl_IssueTracker"/>.</param>
        static partial void OnDTO(this tbl_IssueTracker entity, tbl_IssueTrackerDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="tbl_IssueTracker"/> converted from <see cref="tbl_IssueTrackerDTO"/>.</param>
        static partial void OnEntity(this tbl_IssueTrackerDTO dto, tbl_IssueTracker entity);

        /// <summary>
        /// Converts this instance of <see cref="tbl_IssueTrackerDTO"/> to an instance of <see cref="tbl_IssueTracker"/>.
        /// </summary>
        /// <param name="dto"><see cref="tbl_IssueTrackerDTO"/> to convert.</param>
        public static tbl_IssueTracker ToEntity(this tbl_IssueTrackerDTO dto)
        {
            if (dto == null) return null;

            var entity = new tbl_IssueTracker();

            entity.Id = dto.Id;
            entity.ProjectId = dto.ProjectId;
            entity.StatusId = dto.StatusId;
            entity.PriorityId = dto.PriorityId;
            entity.CategoryId = dto.CategoryId;
            entity.Title = dto.Title;
            entity.Description = dto.Description;
            entity.EndDate = dto.EndDate;
            entity.CreatedOn = dto.CreatedOn;
            entity.ModifiedOn = dto.ModifiedOn;
            entity.Module = dto.Module;
            entity.CreatedBy = dto.CreatedBy;
            entity.ModifiedBy = dto.ModifiedBy;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="tbl_IssueTracker"/> to an instance of <see cref="tbl_IssueTrackerDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="tbl_IssueTracker"/> to convert.</param>
        public static tbl_IssueTrackerDTO ToDTO(this tbl_IssueTracker entity)
        {
            if (entity == null) return null;

            var dto = new tbl_IssueTrackerDTO();

            dto.Id = entity.Id;
            dto.ProjectId = entity.ProjectId;
            dto.StatusId = entity.StatusId;
            dto.PriorityId = entity.PriorityId;
            dto.CategoryId = entity.CategoryId;
            dto.Title = entity.Title;
            dto.Description = entity.Description;
            dto.EndDate = entity.EndDate;
            dto.CreatedOn = entity.CreatedOn;
            dto.ModifiedOn = entity.ModifiedOn;
            dto.Module = entity.Module;
            dto.CreatedBy = entity.CreatedBy;
            dto.ModifiedBy = entity.ModifiedBy;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="tbl_IssueTrackerDTO"/> to an instance of <see cref="tbl_IssueTracker"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<tbl_IssueTracker> ToEntities(this IEnumerable<tbl_IssueTrackerDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="tbl_IssueTracker"/> to an instance of <see cref="tbl_IssueTrackerDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<tbl_IssueTrackerDTO> ToDTOs(this IEnumerable<tbl_IssueTracker> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
