//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/02/12 - 15:04:34
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using ITMCServiceCenter.Web.Database;

namespace ITMCServiceCenter.Web.Domain
{

    /// <summary>
    /// Assembler for <see cref="tbl_Entity"/> and <see cref="tbl_EntityDTO"/>.
    /// </summary>
    public static partial class tbl_Entity_Assembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="tbl_EntityDTO"/> converted from <see cref="tbl_Entity"/>.</param>
        static partial void OnDTO(this tbl_Entity entity, tbl_EntityDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="tbl_Entity"/> converted from <see cref="tbl_EntityDTO"/>.</param>
        static partial void OnEntity(this tbl_EntityDTO dto, tbl_Entity entity);

        /// <summary>
        /// Converts this instance of <see cref="tbl_EntityDTO"/> to an instance of <see cref="tbl_Entity"/>.
        /// </summary>
        /// <param name="dto"><see cref="tbl_EntityDTO"/> to convert.</param>
        public static tbl_Entity ToEntity(this tbl_EntityDTO dto)
        {
            if (dto == null) return null;

            var entity = new tbl_Entity();

            entity.Id = dto.Id;
            entity.TypeMasterId = dto.TypeMasterId;
            entity.Name = dto.Name;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="tbl_Entity"/> to an instance of <see cref="tbl_EntityDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="tbl_Entity"/> to convert.</param>
        public static tbl_EntityDTO ToDTO(this tbl_Entity entity)
        {
            if (entity == null) return null;

            var dto = new tbl_EntityDTO();

            dto.Id = entity.Id;
            dto.TypeMasterId = entity.TypeMasterId;
            dto.Name = entity.Name;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="tbl_EntityDTO"/> to an instance of <see cref="tbl_Entity"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<tbl_Entity> ToEntities(this IEnumerable<tbl_EntityDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="tbl_Entity"/> to an instance of <see cref="tbl_EntityDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<tbl_EntityDTO> ToDTOs(this IEnumerable<tbl_Entity> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
