//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/02/12 - 15:04:33
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using ITMCServiceCenter.Web.Database;

namespace ITMCServiceCenter.Web.Domain
{

    /// <summary>
    /// Assembler for <see cref="tbl_Engineer"/> and <see cref="tbl_EngineerDTO"/>.
    /// </summary>
    public static partial class tbl_Engineer_Assembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="tbl_EngineerDTO"/> converted from <see cref="tbl_Engineer"/>.</param>
        static partial void OnDTO(this tbl_Engineer entity, tbl_EngineerDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="tbl_Engineer"/> converted from <see cref="tbl_EngineerDTO"/>.</param>
        static partial void OnEntity(this tbl_EngineerDTO dto, tbl_Engineer entity);

        /// <summary>
        /// Converts this instance of <see cref="tbl_EngineerDTO"/> to an instance of <see cref="tbl_Engineer"/>.
        /// </summary>
        /// <param name="dto"><see cref="tbl_EngineerDTO"/> to convert.</param>
        public static tbl_Engineer ToEntity(this tbl_EngineerDTO dto)
        {
            if (dto == null) return null;

            var entity = new tbl_Engineer();

            entity.RelateTypeId = dto.RelateTypeId;
            entity.RelatedToId = dto.RelatedToId;
            entity.UserId = dto.UserId;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="tbl_Engineer"/> to an instance of <see cref="tbl_EngineerDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="tbl_Engineer"/> to convert.</param>
        public static tbl_EngineerDTO ToDTO(this tbl_Engineer entity)
        {
            if (entity == null) return null;

            var dto = new tbl_EngineerDTO();

            dto.RelateTypeId = entity.RelateTypeId;
            dto.RelatedToId = entity.RelatedToId;
            dto.UserId = entity.UserId;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="tbl_EngineerDTO"/> to an instance of <see cref="tbl_Engineer"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<tbl_Engineer> ToEntities(this IEnumerable<tbl_EngineerDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="tbl_Engineer"/> to an instance of <see cref="tbl_EngineerDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<tbl_EngineerDTO> ToDTOs(this IEnumerable<tbl_Engineer> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
