//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/02/12 - 15:04:35
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using ITMCServiceCenter.Web.Database;

namespace ITMCServiceCenter.Web.Domain
{

    /// <summary>
    /// Assembler for <see cref="tbl_TypeMaster"/> and <see cref="tbl_TypeMasterDTO"/>.
    /// </summary>
    public static partial class tbl_TypeMaster_Assembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="tbl_TypeMasterDTO"/> converted from <see cref="tbl_TypeMaster"/>.</param>
        static partial void OnDTO(this tbl_TypeMaster entity, tbl_TypeMasterDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="tbl_TypeMaster"/> converted from <see cref="tbl_TypeMasterDTO"/>.</param>
        static partial void OnEntity(this tbl_TypeMasterDTO dto, tbl_TypeMaster entity);

        /// <summary>
        /// Converts this instance of <see cref="tbl_TypeMasterDTO"/> to an instance of <see cref="tbl_TypeMaster"/>.
        /// </summary>
        /// <param name="dto"><see cref="tbl_TypeMasterDTO"/> to convert.</param>
        public static tbl_TypeMaster ToEntity(this tbl_TypeMasterDTO dto)
        {
            if (dto == null) return null;

            var entity = new tbl_TypeMaster();

            entity.Id = dto.Id;
            entity.Type = dto.Type;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="tbl_TypeMaster"/> to an instance of <see cref="tbl_TypeMasterDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="tbl_TypeMaster"/> to convert.</param>
        public static tbl_TypeMasterDTO ToDTO(this tbl_TypeMaster entity)
        {
            if (entity == null) return null;

            var dto = new tbl_TypeMasterDTO();

            dto.Id = entity.Id;
            dto.Type = entity.Type;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="tbl_TypeMasterDTO"/> to an instance of <see cref="tbl_TypeMaster"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<tbl_TypeMaster> ToEntities(this IEnumerable<tbl_TypeMasterDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="tbl_TypeMaster"/> to an instance of <see cref="tbl_TypeMasterDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<tbl_TypeMasterDTO> ToDTOs(this IEnumerable<tbl_TypeMaster> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
