//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/02/12 - 15:04:34
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using ITMCServiceCenter.Web.Database;

namespace ITMCServiceCenter.Web.Domain
{

    /// <summary>
    /// Assembler for <see cref="tbl_Incident"/> and <see cref="tbl_IncidentDTO"/>.
    /// </summary>
    public static partial class tbl_Incident_Assembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="tbl_IncidentDTO"/> converted from <see cref="tbl_Incident"/>.</param>
        static partial void OnDTO(this tbl_Incident entity, tbl_IncidentDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="tbl_Incident"/> converted from <see cref="tbl_IncidentDTO"/>.</param>
        static partial void OnEntity(this tbl_IncidentDTO dto, tbl_Incident entity);

        /// <summary>
        /// Converts this instance of <see cref="tbl_IncidentDTO"/> to an instance of <see cref="tbl_Incident"/>.
        /// </summary>
        /// <param name="dto"><see cref="tbl_IncidentDTO"/> to convert.</param>
        public static tbl_Incident ToEntity(this tbl_IncidentDTO dto)
        {
            if (dto == null) return null;

            var entity = new tbl_Incident();

            entity.Id = dto.Id;
            entity.RequestedBy = dto.RequestedBy;
            entity.LevelId = dto.LevelId;
            entity.StatusId = dto.StatusId;
            entity.ProjectId = dto.ProjectId;
            entity.Title = dto.Title;
            entity.Description = dto.Description;
            entity.StartDate = dto.StartDate;
            entity.EndDate = dto.EndDate;
            entity.EstimatedHours = dto.EstimatedHours;
            entity.PercentComplete = dto.PercentComplete;
            entity.CreatedOn = dto.CreatedOn;
            entity.ModifiedOn = dto.ModifiedOn;
            entity.IncidentOn = dto.IncidentOn;
            entity.CreatedBy = dto.CreatedBy;
            entity.ModifiedBy = dto.ModifiedBy;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="tbl_Incident"/> to an instance of <see cref="tbl_IncidentDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="tbl_Incident"/> to convert.</param>
        public static tbl_IncidentDTO ToDTO(this tbl_Incident entity)
        {
            if (entity == null) return null;

            var dto = new tbl_IncidentDTO();

            dto.Id = entity.Id;
            dto.RequestedBy = entity.RequestedBy;
            dto.LevelId = entity.LevelId;
            dto.StatusId = entity.StatusId;
            dto.ProjectId = entity.ProjectId;
            dto.Title = entity.Title;
            dto.Description = entity.Description;
            dto.StartDate = entity.StartDate;
            dto.EndDate = entity.EndDate;
            dto.EstimatedHours = entity.EstimatedHours;
            dto.PercentComplete = entity.PercentComplete;
            dto.CreatedOn = entity.CreatedOn;
            dto.ModifiedOn = entity.ModifiedOn;
            dto.IncidentOn = entity.IncidentOn;
            dto.CreatedBy = entity.CreatedBy;
            dto.ModifiedBy = entity.ModifiedBy;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="tbl_IncidentDTO"/> to an instance of <see cref="tbl_Incident"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<tbl_Incident> ToEntities(this IEnumerable<tbl_IncidentDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="tbl_Incident"/> to an instance of <see cref="tbl_IncidentDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<tbl_IncidentDTO> ToDTOs(this IEnumerable<tbl_Incident> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
