//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/02/12 - 15:04:34
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using ITMCServiceCenter.Web.Database;

namespace ITMCServiceCenter.Web.Domain
{

    /// <summary>
    /// Assembler for <see cref="tbl_ProjectTaskDocument"/> and <see cref="tbl_ProjectTaskDocumentDTO"/>.
    /// </summary>
    public static partial class tbl_ProjectTaskDocument_Assembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="tbl_ProjectTaskDocumentDTO"/> converted from <see cref="tbl_ProjectTaskDocument"/>.</param>
        static partial void OnDTO(this tbl_ProjectTaskDocument entity, tbl_ProjectTaskDocumentDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="tbl_ProjectTaskDocument"/> converted from <see cref="tbl_ProjectTaskDocumentDTO"/>.</param>
        static partial void OnEntity(this tbl_ProjectTaskDocumentDTO dto, tbl_ProjectTaskDocument entity);

        /// <summary>
        /// Converts this instance of <see cref="tbl_ProjectTaskDocumentDTO"/> to an instance of <see cref="tbl_ProjectTaskDocument"/>.
        /// </summary>
        /// <param name="dto"><see cref="tbl_ProjectTaskDocumentDTO"/> to convert.</param>
        public static tbl_ProjectTaskDocument ToEntity(this tbl_ProjectTaskDocumentDTO dto)
        {
            if (dto == null) return null;

            var entity = new tbl_ProjectTaskDocument();

            entity.Id = dto.Id;
            entity.ProjectTaskId = dto.ProjectTaskId;
            entity.Title = dto.Title;
            entity.Description = dto.Description;
            entity.Path = dto.Path;
            entity.CreatedBy = dto.CreatedBy;
            entity.CreatedOn = dto.CreatedOn;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="tbl_ProjectTaskDocument"/> to an instance of <see cref="tbl_ProjectTaskDocumentDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="tbl_ProjectTaskDocument"/> to convert.</param>
        public static tbl_ProjectTaskDocumentDTO ToDTO(this tbl_ProjectTaskDocument entity)
        {
            if (entity == null) return null;

            var dto = new tbl_ProjectTaskDocumentDTO();

            dto.Id = entity.Id;
            dto.ProjectTaskId = entity.ProjectTaskId;
            dto.Title = entity.Title;
            dto.Description = entity.Description;
            dto.Path = entity.Path;
            dto.CreatedBy = entity.CreatedBy;
            dto.CreatedOn = entity.CreatedOn;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="tbl_ProjectTaskDocumentDTO"/> to an instance of <see cref="tbl_ProjectTaskDocument"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<tbl_ProjectTaskDocument> ToEntities(this IEnumerable<tbl_ProjectTaskDocumentDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="tbl_ProjectTaskDocument"/> to an instance of <see cref="tbl_ProjectTaskDocumentDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<tbl_ProjectTaskDocumentDTO> ToDTOs(this IEnumerable<tbl_ProjectTaskDocument> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
