//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/02/12 - 15:04:35
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using ITMCServiceCenter.Web.Database;

namespace ITMCServiceCenter.Web.Domain
{

    /// <summary>
    /// Assembler for <see cref="tbl_ServiceRequestDocument"/> and <see cref="tbl_ServiceRequestDocumentDTO"/>.
    /// </summary>
    public static partial class tbl_ServiceRequestDocument_Assembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="tbl_ServiceRequestDocumentDTO"/> converted from <see cref="tbl_ServiceRequestDocument"/>.</param>
        static partial void OnDTO(this tbl_ServiceRequestDocument entity, tbl_ServiceRequestDocumentDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="tbl_ServiceRequestDocument"/> converted from <see cref="tbl_ServiceRequestDocumentDTO"/>.</param>
        static partial void OnEntity(this tbl_ServiceRequestDocumentDTO dto, tbl_ServiceRequestDocument entity);

        /// <summary>
        /// Converts this instance of <see cref="tbl_ServiceRequestDocumentDTO"/> to an instance of <see cref="tbl_ServiceRequestDocument"/>.
        /// </summary>
        /// <param name="dto"><see cref="tbl_ServiceRequestDocumentDTO"/> to convert.</param>
        public static tbl_ServiceRequestDocument ToEntity(this tbl_ServiceRequestDocumentDTO dto)
        {
            if (dto == null) return null;

            var entity = new tbl_ServiceRequestDocument();

            entity.Id = dto.Id;
            entity.ServiceRequestId = dto.ServiceRequestId;
            entity.Title = dto.Title;
            entity.Description = dto.Description;
            entity.Path = dto.Path;
            entity.CreatedBy = dto.CreatedBy;
            entity.CreatedOn = dto.CreatedOn;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="tbl_ServiceRequestDocument"/> to an instance of <see cref="tbl_ServiceRequestDocumentDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="tbl_ServiceRequestDocument"/> to convert.</param>
        public static tbl_ServiceRequestDocumentDTO ToDTO(this tbl_ServiceRequestDocument entity)
        {
            if (entity == null) return null;

            var dto = new tbl_ServiceRequestDocumentDTO();

            dto.Id = entity.Id;
            dto.ServiceRequestId = entity.ServiceRequestId;
            dto.Title = entity.Title;
            dto.Description = entity.Description;
            dto.Path = entity.Path;
            dto.CreatedBy = entity.CreatedBy;
            dto.CreatedOn = entity.CreatedOn;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="tbl_ServiceRequestDocumentDTO"/> to an instance of <see cref="tbl_ServiceRequestDocument"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<tbl_ServiceRequestDocument> ToEntities(this IEnumerable<tbl_ServiceRequestDocumentDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="tbl_ServiceRequestDocument"/> to an instance of <see cref="tbl_ServiceRequestDocumentDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<tbl_ServiceRequestDocumentDTO> ToDTOs(this IEnumerable<tbl_ServiceRequestDocument> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
