//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/02/12 - 15:04:33
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using ITMCServiceCenter.Web.Database;

namespace ITMCServiceCenter.Web.Domain
{

    /// <summary>
    /// Assembler for <see cref="tbl_Client"/> and <see cref="tbl_ClientDTO"/>.
    /// </summary>
    public static partial class tbl_Client_Assembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="tbl_ClientDTO"/> converted from <see cref="tbl_Client"/>.</param>
        static partial void OnDTO(this tbl_Client entity, tbl_ClientDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="tbl_Client"/> converted from <see cref="tbl_ClientDTO"/>.</param>
        static partial void OnEntity(this tbl_ClientDTO dto, tbl_Client entity);

        /// <summary>
        /// Converts this instance of <see cref="tbl_ClientDTO"/> to an instance of <see cref="tbl_Client"/>.
        /// </summary>
        /// <param name="dto"><see cref="tbl_ClientDTO"/> to convert.</param>
        public static tbl_Client ToEntity(this tbl_ClientDTO dto)
        {
            if (dto == null) return null;

            var entity = new tbl_Client();

            entity.Id = dto.Id;
            entity.Name = dto.Name;
            entity.Location = dto.Location;
            entity.ContactNo = dto.ContactNo;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="tbl_Client"/> to an instance of <see cref="tbl_ClientDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="tbl_Client"/> to convert.</param>
        public static tbl_ClientDTO ToDTO(this tbl_Client entity)
        {
            if (entity == null) return null;

            var dto = new tbl_ClientDTO();

            dto.Id = entity.Id;
            dto.Name = entity.Name;
            dto.Location = entity.Location;
            dto.ContactNo = entity.ContactNo;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="tbl_ClientDTO"/> to an instance of <see cref="tbl_Client"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<tbl_Client> ToEntities(this IEnumerable<tbl_ClientDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="tbl_Client"/> to an instance of <see cref="tbl_ClientDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<tbl_ClientDTO> ToDTOs(this IEnumerable<tbl_Client> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
