//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/02/12 - 15:04:34
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using ITMCServiceCenter.Web.Database;

namespace ITMCServiceCenter.Web.Domain
{

    /// <summary>
    /// Assembler for <see cref="tbl_IssueTrackerDocument"/> and <see cref="tbl_IssueTrackerDocumentDTO"/>.
    /// </summary>
    public static partial class tbl_IssueTrackerDocument_Assembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="tbl_IssueTrackerDocumentDTO"/> converted from <see cref="tbl_IssueTrackerDocument"/>.</param>
        static partial void OnDTO(this tbl_IssueTrackerDocument entity, tbl_IssueTrackerDocumentDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="tbl_IssueTrackerDocument"/> converted from <see cref="tbl_IssueTrackerDocumentDTO"/>.</param>
        static partial void OnEntity(this tbl_IssueTrackerDocumentDTO dto, tbl_IssueTrackerDocument entity);

        /// <summary>
        /// Converts this instance of <see cref="tbl_IssueTrackerDocumentDTO"/> to an instance of <see cref="tbl_IssueTrackerDocument"/>.
        /// </summary>
        /// <param name="dto"><see cref="tbl_IssueTrackerDocumentDTO"/> to convert.</param>
        public static tbl_IssueTrackerDocument ToEntity(this tbl_IssueTrackerDocumentDTO dto)
        {
            if (dto == null) return null;

            var entity = new tbl_IssueTrackerDocument();

            entity.Id = dto.Id;
            entity.IssueTrackerId = dto.IssueTrackerId;
            entity.Title = dto.Title;
            entity.Description = dto.Description;
            entity.Path = dto.Path;
            entity.CreatedBy = dto.CreatedBy;
            entity.CreatedOn = dto.CreatedOn;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="tbl_IssueTrackerDocument"/> to an instance of <see cref="tbl_IssueTrackerDocumentDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="tbl_IssueTrackerDocument"/> to convert.</param>
        public static tbl_IssueTrackerDocumentDTO ToDTO(this tbl_IssueTrackerDocument entity)
        {
            if (entity == null) return null;

            var dto = new tbl_IssueTrackerDocumentDTO();

            dto.Id = entity.Id;
            dto.IssueTrackerId = entity.IssueTrackerId;
            dto.Title = entity.Title;
            dto.Description = entity.Description;
            dto.Path = entity.Path;
            dto.CreatedBy = entity.CreatedBy;
            dto.CreatedOn = entity.CreatedOn;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="tbl_IssueTrackerDocumentDTO"/> to an instance of <see cref="tbl_IssueTrackerDocument"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<tbl_IssueTrackerDocument> ToEntities(this IEnumerable<tbl_IssueTrackerDocumentDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="tbl_IssueTrackerDocument"/> to an instance of <see cref="tbl_IssueTrackerDocumentDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<tbl_IssueTrackerDocumentDTO> ToDTOs(this IEnumerable<tbl_IssueTrackerDocument> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
