//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/02/12 - 15:04:34
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using ITMCServiceCenter.Web.Database;

namespace ITMCServiceCenter.Web.Domain
{

    /// <summary>
    /// Assembler for <see cref="tbl_ProjectTaskAction"/> and <see cref="tbl_ProjectTaskActionDTO"/>.
    /// </summary>
    public static partial class tbl_ProjectTaskAction_Assembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="tbl_ProjectTaskActionDTO"/> converted from <see cref="tbl_ProjectTaskAction"/>.</param>
        static partial void OnDTO(this tbl_ProjectTaskAction entity, tbl_ProjectTaskActionDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="tbl_ProjectTaskAction"/> converted from <see cref="tbl_ProjectTaskActionDTO"/>.</param>
        static partial void OnEntity(this tbl_ProjectTaskActionDTO dto, tbl_ProjectTaskAction entity);

        /// <summary>
        /// Converts this instance of <see cref="tbl_ProjectTaskActionDTO"/> to an instance of <see cref="tbl_ProjectTaskAction"/>.
        /// </summary>
        /// <param name="dto"><see cref="tbl_ProjectTaskActionDTO"/> to convert.</param>
        public static tbl_ProjectTaskAction ToEntity(this tbl_ProjectTaskActionDTO dto)
        {
            if (dto == null) return null;

            var entity = new tbl_ProjectTaskAction();

            entity.Id = dto.Id;
            entity.ProjectTaskId = dto.ProjectTaskId;
            entity.Action = dto.Action;
            entity.CreatedBy = dto.CreatedBy;
            entity.CreatedOn = dto.CreatedOn;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="tbl_ProjectTaskAction"/> to an instance of <see cref="tbl_ProjectTaskActionDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="tbl_ProjectTaskAction"/> to convert.</param>
        public static tbl_ProjectTaskActionDTO ToDTO(this tbl_ProjectTaskAction entity)
        {
            if (entity == null) return null;

            var dto = new tbl_ProjectTaskActionDTO();

            dto.Id = entity.Id;
            dto.ProjectTaskId = entity.ProjectTaskId;
            dto.Action = entity.Action;
            dto.CreatedBy = entity.CreatedBy;
            dto.CreatedOn = entity.CreatedOn;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="tbl_ProjectTaskActionDTO"/> to an instance of <see cref="tbl_ProjectTaskAction"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<tbl_ProjectTaskAction> ToEntities(this IEnumerable<tbl_ProjectTaskActionDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="tbl_ProjectTaskAction"/> to an instance of <see cref="tbl_ProjectTaskActionDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<tbl_ProjectTaskActionDTO> ToDTOs(this IEnumerable<tbl_ProjectTaskAction> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
