//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/02/12 - 15:04:34
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using ITMCServiceCenter.Web.Database;

namespace ITMCServiceCenter.Web.Domain
{

    /// <summary>
    /// Assembler for <see cref="tbl_IncidentDocument"/> and <see cref="tbl_IncidentDocumentDTO"/>.
    /// </summary>
    public static partial class tbl_IncidentDocument_Assembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="tbl_IncidentDocumentDTO"/> converted from <see cref="tbl_IncidentDocument"/>.</param>
        static partial void OnDTO(this tbl_IncidentDocument entity, tbl_IncidentDocumentDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="tbl_IncidentDocument"/> converted from <see cref="tbl_IncidentDocumentDTO"/>.</param>
        static partial void OnEntity(this tbl_IncidentDocumentDTO dto, tbl_IncidentDocument entity);

        /// <summary>
        /// Converts this instance of <see cref="tbl_IncidentDocumentDTO"/> to an instance of <see cref="tbl_IncidentDocument"/>.
        /// </summary>
        /// <param name="dto"><see cref="tbl_IncidentDocumentDTO"/> to convert.</param>
        public static tbl_IncidentDocument ToEntity(this tbl_IncidentDocumentDTO dto)
        {
            if (dto == null) return null;

            var entity = new tbl_IncidentDocument();

            entity.Id = dto.Id;
            entity.IncidentId = dto.IncidentId;
            entity.Title = dto.Title;
            entity.Description = dto.Description;
            entity.Path = dto.Path;
            entity.CreatedBy = dto.CreatedBy;
            entity.CreatedOn = dto.CreatedOn;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="tbl_IncidentDocument"/> to an instance of <see cref="tbl_IncidentDocumentDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="tbl_IncidentDocument"/> to convert.</param>
        public static tbl_IncidentDocumentDTO ToDTO(this tbl_IncidentDocument entity)
        {
            if (entity == null) return null;

            var dto = new tbl_IncidentDocumentDTO();

            dto.Id = entity.Id;
            dto.IncidentId = entity.IncidentId;
            dto.Title = entity.Title;
            dto.Description = entity.Description;
            dto.Path = entity.Path;
            dto.CreatedBy = entity.CreatedBy;
            dto.CreatedOn = entity.CreatedOn;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="tbl_IncidentDocumentDTO"/> to an instance of <see cref="tbl_IncidentDocument"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<tbl_IncidentDocument> ToEntities(this IEnumerable<tbl_IncidentDocumentDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="tbl_IncidentDocument"/> to an instance of <see cref="tbl_IncidentDocumentDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<tbl_IncidentDocumentDTO> ToDTOs(this IEnumerable<tbl_IncidentDocument> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
