//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/02/12 - 15:04:34
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using ITMCServiceCenter.Web.Database;

namespace ITMCServiceCenter.Web.Domain
{

    /// <summary>
    /// Assembler for <see cref="tbl_ProjectTask"/> and <see cref="tbl_ProjectTaskDTO"/>.
    /// </summary>
    public static partial class tbl_ProjectTask_Assembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="tbl_ProjectTaskDTO"/> converted from <see cref="tbl_ProjectTask"/>.</param>
        static partial void OnDTO(this tbl_ProjectTask entity, tbl_ProjectTaskDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="tbl_ProjectTask"/> converted from <see cref="tbl_ProjectTaskDTO"/>.</param>
        static partial void OnEntity(this tbl_ProjectTaskDTO dto, tbl_ProjectTask entity);

        /// <summary>
        /// Converts this instance of <see cref="tbl_ProjectTaskDTO"/> to an instance of <see cref="tbl_ProjectTask"/>.
        /// </summary>
        /// <param name="dto"><see cref="tbl_ProjectTaskDTO"/> to convert.</param>
        public static tbl_ProjectTask ToEntity(this tbl_ProjectTaskDTO dto)
        {
            if (dto == null) return null;

            var entity = new tbl_ProjectTask();

            entity.Id = dto.Id;
            entity.ProjectId = dto.ProjectId;
            entity.StatusId = dto.StatusId;
            entity.PriorityId = dto.PriorityId;
            entity.TypeId = dto.TypeId;
            entity.QA = dto.QA;
            entity.Title = dto.Title;
            entity.Description = dto.Description;
            entity.StartDate = dto.StartDate;
            entity.EndDate = dto.EndDate;
            entity.EstimatedHours = dto.EstimatedHours;
            entity.EstimatedCost = dto.EstimatedCost;
            entity.PercentComplete = dto.PercentComplete;
            entity.QAStartDate = dto.QAStartDate;
            entity.QAEndDate = dto.QAEndDate;
            entity.CreatedOn = dto.CreatedOn;
            entity.ModifiedOn = dto.ModifiedOn;
            entity.CreatedBy = dto.CreatedBy;
            entity.ModifiedBy = dto.ModifiedBy;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="tbl_ProjectTask"/> to an instance of <see cref="tbl_ProjectTaskDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="tbl_ProjectTask"/> to convert.</param>
        public static tbl_ProjectTaskDTO ToDTO(this tbl_ProjectTask entity)
        {
            if (entity == null) return null;

            var dto = new tbl_ProjectTaskDTO();

            dto.Id = entity.Id;
            dto.ProjectId = entity.ProjectId;
            dto.StatusId = entity.StatusId;
            dto.PriorityId = entity.PriorityId;
            dto.TypeId = entity.TypeId;
            dto.QA = entity.QA;
            dto.Title = entity.Title;
            dto.Description = entity.Description;
            dto.StartDate = entity.StartDate;
            dto.EndDate = entity.EndDate;
            dto.EstimatedHours = entity.EstimatedHours;
            dto.EstimatedCost = entity.EstimatedCost;
            dto.PercentComplete = entity.PercentComplete;
            dto.QAStartDate = entity.QAStartDate;
            dto.QAEndDate = entity.QAEndDate;
            dto.CreatedOn = entity.CreatedOn;
            dto.ModifiedOn = entity.ModifiedOn;
            dto.CreatedBy = entity.CreatedBy;
            dto.ModifiedBy = entity.ModifiedBy;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="tbl_ProjectTaskDTO"/> to an instance of <see cref="tbl_ProjectTask"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<tbl_ProjectTask> ToEntities(this IEnumerable<tbl_ProjectTaskDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="tbl_ProjectTask"/> to an instance of <see cref="tbl_ProjectTaskDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<tbl_ProjectTaskDTO> ToDTOs(this IEnumerable<tbl_ProjectTask> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
