//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/02/12 - 15:04:35
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using ITMCServiceCenter.Web.Database;

namespace ITMCServiceCenter.Web.Domain
{

    /// <summary>
    /// Assembler for <see cref="tbl_ProjectTaskType"/> and <see cref="tbl_ProjectTaskTypeDTO"/>.
    /// </summary>
    public static partial class tbl_ProjectTaskType_Assembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="tbl_ProjectTaskTypeDTO"/> converted from <see cref="tbl_ProjectTaskType"/>.</param>
        static partial void OnDTO(this tbl_ProjectTaskType entity, tbl_ProjectTaskTypeDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="tbl_ProjectTaskType"/> converted from <see cref="tbl_ProjectTaskTypeDTO"/>.</param>
        static partial void OnEntity(this tbl_ProjectTaskTypeDTO dto, tbl_ProjectTaskType entity);

        /// <summary>
        /// Converts this instance of <see cref="tbl_ProjectTaskTypeDTO"/> to an instance of <see cref="tbl_ProjectTaskType"/>.
        /// </summary>
        /// <param name="dto"><see cref="tbl_ProjectTaskTypeDTO"/> to convert.</param>
        public static tbl_ProjectTaskType ToEntity(this tbl_ProjectTaskTypeDTO dto)
        {
            if (dto == null) return null;

            var entity = new tbl_ProjectTaskType();

            entity.Id = dto.Id;
            entity.ProjectId = dto.ProjectId;
            entity.Type = dto.Type;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="tbl_ProjectTaskType"/> to an instance of <see cref="tbl_ProjectTaskTypeDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="tbl_ProjectTaskType"/> to convert.</param>
        public static tbl_ProjectTaskTypeDTO ToDTO(this tbl_ProjectTaskType entity)
        {
            if (entity == null) return null;

            var dto = new tbl_ProjectTaskTypeDTO();

            dto.Id = entity.Id;
            dto.ProjectId = entity.ProjectId;
            dto.Type = entity.Type;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="tbl_ProjectTaskTypeDTO"/> to an instance of <see cref="tbl_ProjectTaskType"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<tbl_ProjectTaskType> ToEntities(this IEnumerable<tbl_ProjectTaskTypeDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="tbl_ProjectTaskType"/> to an instance of <see cref="tbl_ProjectTaskTypeDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<tbl_ProjectTaskTypeDTO> ToDTOs(this IEnumerable<tbl_ProjectTaskType> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
