//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/02/12 - 15:04:35
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using ITMCServiceCenter.Web.Database;

namespace ITMCServiceCenter.Web.Domain
{

    /// <summary>
    /// Assembler for <see cref="tbl_ServiceRequestAction"/> and <see cref="tbl_ServiceRequestActionDTO"/>.
    /// </summary>
    public static partial class tbl_ServiceRequestAction_Assembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="tbl_ServiceRequestActionDTO"/> converted from <see cref="tbl_ServiceRequestAction"/>.</param>
        static partial void OnDTO(this tbl_ServiceRequestAction entity, tbl_ServiceRequestActionDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="tbl_ServiceRequestAction"/> converted from <see cref="tbl_ServiceRequestActionDTO"/>.</param>
        static partial void OnEntity(this tbl_ServiceRequestActionDTO dto, tbl_ServiceRequestAction entity);

        /// <summary>
        /// Converts this instance of <see cref="tbl_ServiceRequestActionDTO"/> to an instance of <see cref="tbl_ServiceRequestAction"/>.
        /// </summary>
        /// <param name="dto"><see cref="tbl_ServiceRequestActionDTO"/> to convert.</param>
        public static tbl_ServiceRequestAction ToEntity(this tbl_ServiceRequestActionDTO dto)
        {
            if (dto == null) return null;

            var entity = new tbl_ServiceRequestAction();

            entity.Id = dto.Id;
            entity.ServiceRequestId = dto.ServiceRequestId;
            entity.Action = dto.Action;
            entity.CreatedBy = dto.CreatedBy;
            entity.CreatedOn = dto.CreatedOn;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="tbl_ServiceRequestAction"/> to an instance of <see cref="tbl_ServiceRequestActionDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="tbl_ServiceRequestAction"/> to convert.</param>
        public static tbl_ServiceRequestActionDTO ToDTO(this tbl_ServiceRequestAction entity)
        {
            if (entity == null) return null;

            var dto = new tbl_ServiceRequestActionDTO();

            dto.Id = entity.Id;
            dto.ServiceRequestId = entity.ServiceRequestId;
            dto.Action = entity.Action;
            dto.CreatedBy = entity.CreatedBy;
            dto.CreatedOn = entity.CreatedOn;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="tbl_ServiceRequestActionDTO"/> to an instance of <see cref="tbl_ServiceRequestAction"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<tbl_ServiceRequestAction> ToEntities(this IEnumerable<tbl_ServiceRequestActionDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="tbl_ServiceRequestAction"/> to an instance of <see cref="tbl_ServiceRequestActionDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<tbl_ServiceRequestActionDTO> ToDTOs(this IEnumerable<tbl_ServiceRequestAction> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
