//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITMCServiceCenter.Web.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.IssueTrackers = new HashSet<IssueTracker>();
        }
    
        public byte ID { get; set; }
        public string Category1 { get; set; }
    
        public virtual ICollection<IssueTracker> IssueTrackers { get; set; }
    }
}
