//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITMCServiceCenter.Web.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangeRequest
    {
        public ChangeRequest()
        {
            this.ChangeRequestActions = new HashSet<ChangeRequestAction>();
            this.ChangeRequestDocuments = new HashSet<ChangeRequestDocument>();
            this.UserMasters = new HashSet<UserMaster>();
        }
    
        public int ID { get; set; }
        public short ProjectID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Approver { get; set; }
        public int RequestedBy { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public short EstimateTime { get; set; }
        public short PercentComplete { get; set; }
        public string Impact { get; set; }
        public int AssignedTo { get; set; }
        public byte PriorityID { get; set; }
        public int PoNo { get; set; }
        public byte StatusID { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual UserMaster UserMaster { get; set; }
        public virtual UserMaster UserMaster1 { get; set; }
        public virtual UserMaster UserMaster2 { get; set; }
        public virtual UserMaster UserMaster3 { get; set; }
        public virtual UserMaster UserMaster4 { get; set; }
        public virtual ICollection<ChangeRequestAction> ChangeRequestActions { get; set; }
        public virtual ICollection<ChangeRequestDocument> ChangeRequestDocuments { get; set; }
        public virtual ICollection<UserMaster> UserMasters { get; set; }
    }
}
