//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITMCServiceCenter.Web.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncidentLevel
    {
        public IncidentLevel()
        {
            this.Incidents = new HashSet<Incident>();
        }
    
        public byte ID { get; set; }
        public string Level { get; set; }
    
        public virtual ICollection<Incident> Incidents { get; set; }
    }
}
