//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITMCServiceCenter.Web.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incident
    {
        public Incident()
        {
            this.IncidentActions = new HashSet<IncidentAction>();
            this.IncidentDocuments = new HashSet<IncidentDocument>();
            this.UserMasters = new HashSet<UserMaster>();
        }
    
        public int ID { get; set; }
        public short ProjectID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public byte IncidentLevelID { get; set; }
        public byte LevelID { get; set; }
        public byte StatusID { get; set; }
        public int AssignedTo { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public short EstimateHours { get; set; }
        public int RequestedBy { get; set; }
        public byte PercentComplete { get; set; }
        public Nullable<byte> RelateType { get; set; }
        public Nullable<int> RelatedTo { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual IncidentLevel IncidentLevel { get; set; }
        public virtual Project Project { get; set; }
        public virtual Status Status { get; set; }
        public virtual UserMaster UserMaster { get; set; }
        public virtual UserMaster UserMaster1 { get; set; }
        public virtual UserMaster UserMaster2 { get; set; }
        public virtual UserMaster UserMaster3 { get; set; }
        public virtual ICollection<IncidentAction> IncidentActions { get; set; }
        public virtual ICollection<IncidentDocument> IncidentDocuments { get; set; }
        public virtual ICollection<UserMaster> UserMasters { get; set; }
    }
}
