//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITMCServiceCenter.Web.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.Incidents = new HashSet<Incident>();
            this.IssueTrackers = new HashSet<IssueTracker>();
            this.ProjectDocuments = new HashSet<ProjectDocument>();
            this.ProjectTasks = new HashSet<ProjectTask>();
            this.ServiceRequests = new HashSet<ServiceRequest>();
            this.Teams = new HashSet<Team>();
            this.Teams1 = new HashSet<Team>();
        }
    
        public short ID { get; set; }
        public int ClientID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public short EstimatedHours { get; set; }
        public int EstimatedCost { get; set; }
        public Nullable<int> Manager { get; set; }
        public Nullable<int> PoNo { get; set; }
        public string Site { get; set; }
        public Nullable<int> Approver { get; set; }
        public Nullable<int> QA { get; set; }
        public byte StatusID { get; set; }
        public byte TypeID { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ICollection<Incident> Incidents { get; set; }
        public virtual ICollection<IssueTracker> IssueTrackers { get; set; }
        public virtual ProjectType ProjectType { get; set; }
        public virtual UserMaster UserMaster { get; set; }
        public virtual UserMaster UserMaster1 { get; set; }
        public virtual UserMaster UserMaster2 { get; set; }
        public virtual UserMaster UserMaster3 { get; set; }
        public virtual UserMaster UserMaster4 { get; set; }
        public virtual ICollection<ProjectDocument> ProjectDocuments { get; set; }
        public virtual ICollection<ProjectTask> ProjectTasks { get; set; }
        public virtual ICollection<ServiceRequest> ServiceRequests { get; set; }
        public virtual ICollection<Team> Teams { get; set; }
        public virtual ICollection<Team> Teams1 { get; set; }
    }
}
