//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITMCServiceCenter.Web.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectTaskType
    {
        public ProjectTaskType()
        {
            this.ProjectTasks = new HashSet<ProjectTask>();
        }
    
        public byte ID { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<ProjectTask> ProjectTasks { get; set; }
    }
}
