//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITMCServiceCenter.Web.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Incident
    {
        public tbl_Incident()
        {
            this.tbl_IncidentAction = new HashSet<tbl_IncidentAction>();
            this.tbl_IncidentDocument = new HashSet<tbl_IncidentDocument>();
        }
    
        public int Id { get; set; }
        public int RequestedBy { get; set; }
        public short LevelId { get; set; }
        public short StatusId { get; set; }
        public short ProjectId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<short> EstimatedHours { get; set; }
        public byte PercentComplete { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public System.DateTime IncidentOn { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual tbl_Entity tbl_Entity { get; set; }
        public virtual tbl_Project tbl_Project { get; set; }
        public virtual tbl_UserMaster tbl_UserMaster { get; set; }
        public virtual ICollection<tbl_IncidentAction> tbl_IncidentAction { get; set; }
        public virtual ICollection<tbl_IncidentDocument> tbl_IncidentDocument { get; set; }
    }
}
