//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITMCServiceCenter.Web.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_IssueTracker
    {
        public tbl_IssueTracker()
        {
            this.tbl_IssueTrackerAction = new HashSet<tbl_IssueTrackerAction>();
            this.tbl_IssueTrackerDocument = new HashSet<tbl_IssueTrackerDocument>();
        }
    
        public int Id { get; set; }
        public short ProjectId { get; set; }
        public short StatusId { get; set; }
        public short PriorityId { get; set; }
        public short CategoryId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string Module { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual tbl_Entity tbl_Entity { get; set; }
        public virtual tbl_Entity tbl_Entity1 { get; set; }
        public virtual tbl_Entity tbl_Entity2 { get; set; }
        public virtual tbl_Project tbl_Project { get; set; }
        public virtual ICollection<tbl_IssueTrackerAction> tbl_IssueTrackerAction { get; set; }
        public virtual ICollection<tbl_IssueTrackerDocument> tbl_IssueTrackerDocument { get; set; }
    }
}
