//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITMCServiceCenter.Web.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ChangeRequest
    {
        public tbl_ChangeRequest()
        {
            this.tbl_ChangeRequestAction = new HashSet<tbl_ChangeRequestAction>();
            this.tbl_ChangeRequestDocument = new HashSet<tbl_ChangeRequestDocument>();
        }
    
        public int Id { get; set; }
        public int RequestedBy { get; set; }
        public Nullable<int> Approver { get; set; }
        public int ChangeWriter { get; set; }
        public short ProjectId { get; set; }
        public short PriorityId { get; set; }
        public short StatusId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public short EstimatedHours { get; set; }
        public byte PercentComplete { get; set; }
        public string Impact { get; set; }
        public string PoNo { get; set; }
        public System.DateTime RequestedOn { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual tbl_Entity tbl_Entity { get; set; }
        public virtual tbl_Entity tbl_Entity1 { get; set; }
        public virtual tbl_Project tbl_Project { get; set; }
        public virtual tbl_UserMaster tbl_UserMaster { get; set; }
        public virtual tbl_UserMaster tbl_UserMaster1 { get; set; }
        public virtual tbl_UserMaster tbl_UserMaster2 { get; set; }
        public virtual ICollection<tbl_ChangeRequestAction> tbl_ChangeRequestAction { get; set; }
        public virtual ICollection<tbl_ChangeRequestDocument> tbl_ChangeRequestDocument { get; set; }
    }
}
