//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITMCServiceCenter.Web.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Team
    {
        public tbl_Team()
        {
            this.tbl_TeamMember = new HashSet<tbl_TeamMember>();
        }
    
        public int Id { get; set; }
        public byte RelatedTypeId { get; set; }
        public int RelatedToId { get; set; }
        public short TypeId { get; set; }
    
        public virtual tbl_Entity tbl_Entity { get; set; }
        public virtual tbl_TypeMaster tbl_TypeMaster { get; set; }
        public virtual ICollection<tbl_TeamMember> tbl_TeamMember { get; set; }
    }
}
