//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITMCServiceCenter.Web.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Project
    {
        public tbl_Project()
        {
            this.tbl_ChangeRequest = new HashSet<tbl_ChangeRequest>();
            this.tbl_Incident = new HashSet<tbl_Incident>();
            this.tbl_IssueTracker = new HashSet<tbl_IssueTracker>();
            this.tbl_ProjectDocument = new HashSet<tbl_ProjectDocument>();
            this.tbl_ProjectTask = new HashSet<tbl_ProjectTask>();
            this.tbl_ProjectTaskType = new HashSet<tbl_ProjectTaskType>();
            this.tbl_ServiceRequest = new HashSet<tbl_ServiceRequest>();
            this.tbl_ServiceRequest1 = new HashSet<tbl_ServiceRequest>();
        }
    
        public short Id { get; set; }
        public int ClientId { get; set; }
        public short StatusId { get; set; }
        public short TypeId { get; set; }
        public Nullable<int> Manager { get; set; }
        public Nullable<int> Approver { get; set; }
        public Nullable<int> QA { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public short EstimatedHours { get; set; }
        public Nullable<int> EstimatedCost { get; set; }
        public string PoNo { get; set; }
        public string Site { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual ICollection<tbl_ChangeRequest> tbl_ChangeRequest { get; set; }
        public virtual tbl_Client tbl_Client { get; set; }
        public virtual tbl_Entity tbl_Entity { get; set; }
        public virtual tbl_Entity tbl_Entity1 { get; set; }
        public virtual ICollection<tbl_Incident> tbl_Incident { get; set; }
        public virtual ICollection<tbl_IssueTracker> tbl_IssueTracker { get; set; }
        public virtual tbl_UserMaster tbl_UserMaster { get; set; }
        public virtual tbl_UserMaster tbl_UserMaster1 { get; set; }
        public virtual tbl_UserMaster tbl_UserMaster2 { get; set; }
        public virtual ICollection<tbl_ProjectDocument> tbl_ProjectDocument { get; set; }
        public virtual ICollection<tbl_ProjectTask> tbl_ProjectTask { get; set; }
        public virtual ICollection<tbl_ProjectTaskType> tbl_ProjectTaskType { get; set; }
        public virtual ICollection<tbl_ServiceRequest> tbl_ServiceRequest { get; set; }
        public virtual ICollection<tbl_ServiceRequest> tbl_ServiceRequest1 { get; set; }
    }
}
