//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITMCServiceCenter.Web.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Assignee
    {
        public byte RelateTypeId { get; set; }
        public int RelatedToId { get; set; }
        public int UserId { get; set; }
    
        public virtual tbl_TypeMaster tbl_TypeMaster { get; set; }
        public virtual tbl_UserMaster tbl_UserMaster { get; set; }
    }
}
