//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITMCServiceCenter.Web.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TypeMaster
    {
        public tbl_TypeMaster()
        {
            this.tbl_Assignee = new HashSet<tbl_Assignee>();
            this.tbl_Engineer = new HashSet<tbl_Engineer>();
            this.tbl_Entity = new HashSet<tbl_Entity>();
            this.tbl_Team = new HashSet<tbl_Team>();
        }
    
        public byte Id { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<tbl_Assignee> tbl_Assignee { get; set; }
        public virtual ICollection<tbl_Engineer> tbl_Engineer { get; set; }
        public virtual ICollection<tbl_Entity> tbl_Entity { get; set; }
        public virtual ICollection<tbl_Team> tbl_Team { get; set; }
    }
}
