//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITMCServiceCenter.Web.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ProjectTask
    {
        public tbl_ProjectTask()
        {
            this.tbl_ProjectTaskAction = new HashSet<tbl_ProjectTaskAction>();
            this.tbl_ProjectTaskDocument = new HashSet<tbl_ProjectTaskDocument>();
        }
    
        public int Id { get; set; }
        public short ProjectId { get; set; }
        public short StatusId { get; set; }
        public short PriorityId { get; set; }
        public short TypeId { get; set; }
        public Nullable<int> QA { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<short> EstimatedHours { get; set; }
        public Nullable<short> EstimatedCost { get; set; }
        public byte PercentComplete { get; set; }
        public Nullable<System.DateTime> QAStartDate { get; set; }
        public Nullable<System.DateTime> QAEndDate { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual tbl_Entity tbl_Entity { get; set; }
        public virtual tbl_Entity tbl_Entity1 { get; set; }
        public virtual tbl_Project tbl_Project { get; set; }
        public virtual tbl_UserMaster tbl_UserMaster { get; set; }
        public virtual ICollection<tbl_ProjectTaskAction> tbl_ProjectTaskAction { get; set; }
        public virtual ICollection<tbl_ProjectTaskDocument> tbl_ProjectTaskDocument { get; set; }
    }
}
