//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITMCServiceCenter.Web.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ServiceRequest
    {
        public tbl_ServiceRequest()
        {
            this.tbl_ServiceRequestAction = new HashSet<tbl_ServiceRequestAction>();
            this.tbl_ServiceRequestDocument = new HashSet<tbl_ServiceRequestDocument>();
        }
    
        public int Id { get; set; }
        public int RequestedBy { get; set; }
        public short ProjectId { get; set; }
        public short StatusId { get; set; }
        public short PriorityId { get; set; }
        public Nullable<short> PreviousStatusId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public short EstimatedHours { get; set; }
        public byte PercentComplete { get; set; }
        public int PoNo { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public System.DateTime RequestedOn { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual tbl_Entity tbl_Entity { get; set; }
        public virtual tbl_Entity tbl_Entity1 { get; set; }
        public virtual tbl_Entity tbl_Entity2 { get; set; }
        public virtual tbl_Project tbl_Project { get; set; }
        public virtual tbl_Project tbl_Project1 { get; set; }
        public virtual tbl_UserMaster tbl_UserMaster { get; set; }
        public virtual ICollection<tbl_ServiceRequestAction> tbl_ServiceRequestAction { get; set; }
        public virtual ICollection<tbl_ServiceRequestDocument> tbl_ServiceRequestDocument { get; set; }
    }
}
