//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITMCServiceCenter.Web.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Entity
    {
        public tbl_Entity()
        {
            this.tbl_ChangeRequest = new HashSet<tbl_ChangeRequest>();
            this.tbl_ChangeRequest1 = new HashSet<tbl_ChangeRequest>();
            this.tbl_Incident = new HashSet<tbl_Incident>();
            this.tbl_IssueTracker = new HashSet<tbl_IssueTracker>();
            this.tbl_IssueTracker1 = new HashSet<tbl_IssueTracker>();
            this.tbl_IssueTracker2 = new HashSet<tbl_IssueTracker>();
            this.tbl_Project = new HashSet<tbl_Project>();
            this.tbl_Project1 = new HashSet<tbl_Project>();
            this.tbl_ProjectTask = new HashSet<tbl_ProjectTask>();
            this.tbl_ProjectTask1 = new HashSet<tbl_ProjectTask>();
            this.tbl_ServiceRequest = new HashSet<tbl_ServiceRequest>();
            this.tbl_ServiceRequest1 = new HashSet<tbl_ServiceRequest>();
            this.tbl_ServiceRequest2 = new HashSet<tbl_ServiceRequest>();
            this.tbl_Team = new HashSet<tbl_Team>();
            this.tbl_UserMaster = new HashSet<tbl_UserMaster>();
            this.tbl_UserMaster1 = new HashSet<tbl_UserMaster>();
        }
    
        public short Id { get; set; }
        public byte TypeMasterId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<tbl_ChangeRequest> tbl_ChangeRequest { get; set; }
        public virtual ICollection<tbl_ChangeRequest> tbl_ChangeRequest1 { get; set; }
        public virtual tbl_TypeMaster tbl_TypeMaster { get; set; }
        public virtual ICollection<tbl_Incident> tbl_Incident { get; set; }
        public virtual ICollection<tbl_IssueTracker> tbl_IssueTracker { get; set; }
        public virtual ICollection<tbl_IssueTracker> tbl_IssueTracker1 { get; set; }
        public virtual ICollection<tbl_IssueTracker> tbl_IssueTracker2 { get; set; }
        public virtual ICollection<tbl_Project> tbl_Project { get; set; }
        public virtual ICollection<tbl_Project> tbl_Project1 { get; set; }
        public virtual ICollection<tbl_ProjectTask> tbl_ProjectTask { get; set; }
        public virtual ICollection<tbl_ProjectTask> tbl_ProjectTask1 { get; set; }
        public virtual ICollection<tbl_ServiceRequest> tbl_ServiceRequest { get; set; }
        public virtual ICollection<tbl_ServiceRequest> tbl_ServiceRequest1 { get; set; }
        public virtual ICollection<tbl_ServiceRequest> tbl_ServiceRequest2 { get; set; }
        public virtual ICollection<tbl_Team> tbl_Team { get; set; }
        public virtual ICollection<tbl_UserMaster> tbl_UserMaster { get; set; }
        public virtual ICollection<tbl_UserMaster> tbl_UserMaster1 { get; set; }
    }
}
