//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITMCServiceCenter.Web.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamType
    {
        public TeamType()
        {
            this.Teams = new HashSet<Team>();
        }
    
        public byte ID { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<Team> Teams { get; set; }
    }
}
