//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITMCServiceCenter.Web.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public short ProjectID { get; set; }
        public int UserID { get; set; }
        public byte TypeID { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Project Project1 { get; set; }
        public virtual TeamType TeamType { get; set; }
        public virtual UserMaster UserMaster { get; set; }
    }
}
