//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITMCServiceCenter.Web.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMaster
    {
        public UserMaster()
        {
            this.ChangeRequests = new HashSet<ChangeRequest>();
            this.ChangeRequests1 = new HashSet<ChangeRequest>();
            this.ChangeRequests2 = new HashSet<ChangeRequest>();
            this.ChangeRequests3 = new HashSet<ChangeRequest>();
            this.ChangeRequests4 = new HashSet<ChangeRequest>();
            this.ChangeRequestActions = new HashSet<ChangeRequestAction>();
            this.ChangeRequestDocuments = new HashSet<ChangeRequestDocument>();
            this.Incidents = new HashSet<Incident>();
            this.Incidents1 = new HashSet<Incident>();
            this.Incidents2 = new HashSet<Incident>();
            this.Incidents3 = new HashSet<Incident>();
            this.IncidentActions = new HashSet<IncidentAction>();
            this.IncidentDocuments = new HashSet<IncidentDocument>();
            this.IssueTrackerActions = new HashSet<IssueTrackerAction>();
            this.IssueTrackerDocuments = new HashSet<IssueTrackerDocument>();
            this.Projects = new HashSet<Project>();
            this.Projects1 = new HashSet<Project>();
            this.Projects2 = new HashSet<Project>();
            this.Projects3 = new HashSet<Project>();
            this.Projects4 = new HashSet<Project>();
            this.ProjectDocuments = new HashSet<ProjectDocument>();
            this.ProjectTasks = new HashSet<ProjectTask>();
            this.ProjectTasks1 = new HashSet<ProjectTask>();
            this.ProjectTasks2 = new HashSet<ProjectTask>();
            this.ProjectTasks3 = new HashSet<ProjectTask>();
            this.ProjectTasks4 = new HashSet<ProjectTask>();
            this.ProjectTaskActions = new HashSet<ProjectTaskAction>();
            this.ProjectTaskDocuments = new HashSet<ProjectTaskDocument>();
            this.ServiceRequests = new HashSet<ServiceRequest>();
            this.ServiceRequests1 = new HashSet<ServiceRequest>();
            this.ServiceRequests2 = new HashSet<ServiceRequest>();
            this.ServiceRequests3 = new HashSet<ServiceRequest>();
            this.ServiceRequests4 = new HashSet<ServiceRequest>();
            this.ServiceRequestActions = new HashSet<ServiceRequestAction>();
            this.ServiceRequestDocuments = new HashSet<ServiceRequestDocument>();
            this.Teams = new HashSet<Team>();
            this.ChangeRequests5 = new HashSet<ChangeRequest>();
            this.Incidents4 = new HashSet<Incident>();
            this.IssueTrackers = new HashSet<IssueTracker>();
            this.ServiceRequests5 = new HashSet<ServiceRequest>();
        }
    
        public int ID { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public byte DesignationID { get; set; }
        public bool IsClient { get; set; }
        public bool IsDisable { get; set; }
        public byte RoleID { get; set; }
    
        public virtual ICollection<ChangeRequest> ChangeRequests { get; set; }
        public virtual ICollection<ChangeRequest> ChangeRequests1 { get; set; }
        public virtual ICollection<ChangeRequest> ChangeRequests2 { get; set; }
        public virtual ICollection<ChangeRequest> ChangeRequests3 { get; set; }
        public virtual ICollection<ChangeRequest> ChangeRequests4 { get; set; }
        public virtual ICollection<ChangeRequestAction> ChangeRequestActions { get; set; }
        public virtual ICollection<ChangeRequestDocument> ChangeRequestDocuments { get; set; }
        public virtual DesignationMaster DesignationMaster { get; set; }
        public virtual ICollection<Incident> Incidents { get; set; }
        public virtual ICollection<Incident> Incidents1 { get; set; }
        public virtual ICollection<Incident> Incidents2 { get; set; }
        public virtual ICollection<Incident> Incidents3 { get; set; }
        public virtual ICollection<IncidentAction> IncidentActions { get; set; }
        public virtual ICollection<IncidentDocument> IncidentDocuments { get; set; }
        public virtual ICollection<IssueTrackerAction> IssueTrackerActions { get; set; }
        public virtual ICollection<IssueTrackerDocument> IssueTrackerDocuments { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
        public virtual ICollection<Project> Projects1 { get; set; }
        public virtual ICollection<Project> Projects2 { get; set; }
        public virtual ICollection<Project> Projects3 { get; set; }
        public virtual ICollection<Project> Projects4 { get; set; }
        public virtual ICollection<ProjectDocument> ProjectDocuments { get; set; }
        public virtual ICollection<ProjectTask> ProjectTasks { get; set; }
        public virtual ICollection<ProjectTask> ProjectTasks1 { get; set; }
        public virtual ICollection<ProjectTask> ProjectTasks2 { get; set; }
        public virtual ICollection<ProjectTask> ProjectTasks3 { get; set; }
        public virtual ICollection<ProjectTask> ProjectTasks4 { get; set; }
        public virtual ICollection<ProjectTaskAction> ProjectTaskActions { get; set; }
        public virtual ICollection<ProjectTaskDocument> ProjectTaskDocuments { get; set; }
        public virtual RoleMaster RoleMaster { get; set; }
        public virtual ICollection<ServiceRequest> ServiceRequests { get; set; }
        public virtual ICollection<ServiceRequest> ServiceRequests1 { get; set; }
        public virtual ICollection<ServiceRequest> ServiceRequests2 { get; set; }
        public virtual ICollection<ServiceRequest> ServiceRequests3 { get; set; }
        public virtual ICollection<ServiceRequest> ServiceRequests4 { get; set; }
        public virtual ICollection<ServiceRequestAction> ServiceRequestActions { get; set; }
        public virtual ICollection<ServiceRequestDocument> ServiceRequestDocuments { get; set; }
        public virtual ICollection<Team> Teams { get; set; }
        public virtual ICollection<ChangeRequest> ChangeRequests5 { get; set; }
        public virtual ICollection<Incident> Incidents4 { get; set; }
        public virtual ICollection<IssueTracker> IssueTrackers { get; set; }
        public virtual ICollection<ServiceRequest> ServiceRequests5 { get; set; }
    }
}
