//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/02/12 - 15:04:27
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace ITMCServiceCenter.Web.Domain
{
    [DataContract()]
    public partial class tbl_EntityDTO : CommonModel
    {
        [DataMember()]
        public Int16 Id { get; set; }

        [DataMember()]
        public Byte TypeMasterId { get; set; }

        [DataMember()]
        public String Name { get; set; }

        [DataMember()]
        public List<tbl_ChangeRequestDTO> tbl_ChangeRequest { get; set; }

        [DataMember()]
        public List<tbl_ChangeRequestDTO> tbl_ChangeRequest1 { get; set; }

        [DataMember()]
        public tbl_TypeMasterDTO tbl_TypeMaster { get; set; }

        [DataMember()]
        public List<tbl_IncidentDTO> tbl_Incident { get; set; }

        [DataMember()]
        public List<tbl_IssueTrackerDTO> tbl_IssueTracker { get; set; }

        [DataMember()]
        public List<tbl_IssueTrackerDTO> tbl_IssueTracker1 { get; set; }

        [DataMember()]
        public List<tbl_IssueTrackerDTO> tbl_IssueTracker2 { get; set; }

        [DataMember()]
        public List<tbl_ProjectDTO> tbl_Project { get; set; }

        [DataMember()]
        public List<tbl_ProjectDTO> tbl_Project1 { get; set; }

        [DataMember()]
        public List<tbl_ProjectTaskDTO> tbl_ProjectTask { get; set; }

        [DataMember()]
        public List<tbl_ProjectTaskDTO> tbl_ProjectTask1 { get; set; }

        [DataMember()]
        public List<tbl_ServiceRequestDTO> tbl_ServiceRequest { get; set; }

        [DataMember()]
        public List<tbl_ServiceRequestDTO> tbl_ServiceRequest1 { get; set; }

        [DataMember()]
        public List<tbl_ServiceRequestDTO> tbl_ServiceRequest2 { get; set; }

        [DataMember()]
        public List<tbl_TeamDTO> tbl_Team { get; set; }

        [DataMember()]
        public List<tbl_UserMasterDTO> tbl_UserMaster { get; set; }

        [DataMember()]
        public List<tbl_UserMasterDTO> tbl_UserMaster1 { get; set; }
    }
}
