//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/02/12 - 15:04:29
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace ITMCServiceCenter.Web.Domain
{
    [DataContract()]
    public partial class tbl_ProjectDTO : CommonModel
    {
        [DataMember()]
        public Int16 Id { get; set; }

        [DataMember()]
        public Int32 ClientId { get; set; }

        [DataMember()]
        public Int16 StatusId { get; set; }

        [DataMember()]
        public Int16 TypeId { get; set; }

        [DataMember()]
        public Nullable<Int32> Manager { get; set; }

        [DataMember()]
        public Nullable<Int32> Approver { get; set; }

        [DataMember()]
        public Nullable<Int32> QA { get; set; }

        [DataMember()]
        public String CreatedBy { get; set; }

        [DataMember()]
        public String ModifiedBy { get; set; }

        [DataMember()]
        public String Title { get; set; }

        [DataMember()]
        public String Description { get; set; }

        [DataMember()]
        public DateTime StartDate { get; set; }

        [DataMember()]
        public Nullable<DateTime> EndDate { get; set; }

        [DataMember()]
        public Int16 EstimatedHours { get; set; }

        [DataMember()]
        public Nullable<Int32> EstimatedCost { get; set; }

        [DataMember()]
        public String PoNo { get; set; }

        [DataMember()]
        public String Site { get; set; }

        [DataMember()]
        public DateTime CreatedOn { get; set; }

        [DataMember()]
        public Nullable<DateTime> ModifiedOn { get; set; }

        [DataMember()]
        public List<tbl_ChangeRequestDTO> tbl_ChangeRequest { get; set; }

        [DataMember()]
        public tbl_ClientDTO tbl_Client { get; set; }

        [DataMember()]
        public tbl_EntityDTO tbl_Entity { get; set; }

        [DataMember()]
        public tbl_EntityDTO tbl_Entity1 { get; set; }

        [DataMember()]
        public List<tbl_IncidentDTO> tbl_Incident { get; set; }

        [DataMember()]
        public List<tbl_IssueTrackerDTO> tbl_IssueTracker { get; set; }

        [DataMember()]
        public tbl_UserMasterDTO tbl_UserMaster { get; set; }

        [DataMember()]
        public tbl_UserMasterDTO tbl_UserMaster1 { get; set; }

        [DataMember()]
        public tbl_UserMasterDTO tbl_UserMaster2 { get; set; }

        [DataMember()]
        public List<tbl_ProjectDocumentDTO> tbl_ProjectDocument { get; set; }

        [DataMember()]
        public List<tbl_ProjectTaskDTO> tbl_ProjectTask { get; set; }

        [DataMember()]
        public List<tbl_ProjectTaskTypeDTO> tbl_ProjectTaskType { get; set; }

        [DataMember()]
        public List<tbl_ServiceRequestDTO> tbl_ServiceRequest { get; set; }

        [DataMember()]
        public List<tbl_ServiceRequestDTO> tbl_ServiceRequest1 { get; set; }
    }
}
