//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/02/12 - 15:04:28
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace ITMCServiceCenter.Web.Domain
{
    [DataContract()]
    public partial class tbl_IssueTrackerDTO : CommonModel
    {
        [DataMember()]
        public int Id { get; set; }

        [DataMember()]
        public short ProjectId { get; set; }

        [DataMember()]
        public short StatusId { get; set; }

        [DataMember()]
        public short PriorityId { get; set; }

        [DataMember()]
        public short CategoryId { get; set; }

        [DataMember()]
        public string Title { get; set; }

        [DataMember()]
        public string Description { get; set; }

        [DataMember()]
        public Nullable<DateTime> EndDate { get; set; }

        [DataMember()]
        public DateTime CreatedOn { get; set; }

        [DataMember()]
        public Nullable<DateTime> ModifiedOn { get; set; }

        [DataMember()]
        public string Module { get; set; }

        [DataMember()]
        public string CreatedBy { get; set; }

        [DataMember()]
        public string ModifiedBy { get; set; }
    }
}
