//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/02/12 - 15:04:33
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace ITMCServiceCenter.Web.Domain
{
    [DataContract()]
    public partial class tbl_UserMasterDTO : CommonModel
    {
        [DataMember()]
        public Int32 Id { get; set; }

        [DataMember()]
        public Int16 DesignationId { get; set; }

        [DataMember()]
        public Int16 RoleId { get; set; }

        [DataMember()]
        public String UserName { get; set; }

        [DataMember()]
        public String Password { get; set; }

        [DataMember()]
        public String FirstName { get; set; }

        [DataMember()]
        public String LastName { get; set; }

        [DataMember()]
        public Boolean IsClient { get; set; }

        [DataMember()]
        public Boolean IsDisable { get; set; }

        [DataMember()]
        public List<tbl_AssigneeDTO> tbl_Assignee { get; set; }

        [DataMember()]
        public List<tbl_ChangeRequestDTO> tbl_ChangeRequest { get; set; }

        [DataMember()]
        public List<tbl_ChangeRequestDTO> tbl_ChangeRequest1 { get; set; }

        [DataMember()]
        public List<tbl_ChangeRequestDTO> tbl_ChangeRequest2 { get; set; }

        [DataMember()]
        public List<tbl_EngineerDTO> tbl_Engineer { get; set; }

        [DataMember()]
        public tbl_EntityDTO tbl_Entity { get; set; }

        [DataMember()]
        public tbl_EntityDTO tbl_Entity1 { get; set; }

        [DataMember()]
        public List<tbl_IncidentDTO> tbl_Incident { get; set; }

        [DataMember()]
        public List<tbl_ProjectDTO> tbl_Project { get; set; }

        [DataMember()]
        public List<tbl_ProjectDTO> tbl_Project1 { get; set; }

        [DataMember()]
        public List<tbl_ProjectDTO> tbl_Project2 { get; set; }

        [DataMember()]
        public List<tbl_ProjectTaskDTO> tbl_ProjectTask { get; set; }

        [DataMember()]
        public List<tbl_ServiceRequestDTO> tbl_ServiceRequest { get; set; }

        [DataMember()]
        public List<tbl_TeamMemberDTO> tbl_TeamMember { get; set; }
    }
}
