//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/02/12 - 15:04:32
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace ITMCServiceCenter.Web.Domain
{
    [DataContract()]
    public partial class tbl_TypeMasterDTO : CommonModel
    {
        [DataMember()]
        public Byte Id { get; set; }

        [DataMember()]
        public String Type { get; set; }

        [DataMember()]
        public List<tbl_AssigneeDTO> tbl_Assignee { get; set; }

        [DataMember()]
        public List<tbl_EngineerDTO> tbl_Engineer { get; set; }

        [DataMember()]
        public List<tbl_EntityDTO> tbl_Entity { get; set; }

        [DataMember()]
        public List<tbl_TeamDTO> tbl_Team { get; set; }
    }
}
