//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/02/12 - 15:04:26
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace ITMCServiceCenter.Web.Domain
{
    [DataContract()]
    public partial class tbl_AssigneeDTO : CommonModel
    {
        [DataMember()]
        public Byte RelateTypeId { get; set; }

        [DataMember()]
        public Int32 RelatedToId { get; set; }

        [DataMember()]
        public Int32 UserId { get; set; }

        [DataMember()]
        public tbl_TypeMasterDTO tbl_TypeMaster { get; set; }

        [DataMember()]
        public tbl_UserMasterDTO tbl_UserMaster { get; set; }
    }
}
